// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBiriYcD4JDJkZQYH9ayjiURTB5GE9gdg',
    appId: '1:513181349032:web:3fd6c21f0bc414ebe5be9d',
    messagingSenderId: '513181349032',
    projectId: 'my-resturant-74be1',
    authDomain: 'my-resturant-74be1.firebaseapp.com',
    storageBucket: 'my-resturant-74be1.appspot.com',
    measurementId: 'G-MET8X8ZXP6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1snvA-YwA1lGFEfxTpDslyp16n9FdjDY',
    appId: '1:513181349032:ios:042a876f24d2e0d3e5be9d',
    messagingSenderId: '513181349032',
    projectId: 'my-resturant-74be1',
    storageBucket: 'my-resturant-74be1.appspot.com',
    iosBundleId: 'com.app.aiEnabledRestaurantControlAndOptimization',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBiriYcD4JDJkZQYH9ayjiURTB5GE9gdg',
    appId: '1:513181349032:web:935c6b5cadab8beee5be9d',
    messagingSenderId: '513181349032',
    projectId: 'my-resturant-74be1',
    authDomain: 'my-resturant-74be1.firebaseapp.com',
    storageBucket: 'my-resturant-74be1.appspot.com',
    measurementId: 'G-9Y32JRHZWT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1snvA-YwA1lGFEfxTpDslyp16n9FdjDY',
    appId: '1:513181349032:ios:042a876f24d2e0d3e5be9d',
    messagingSenderId: '513181349032',
    projectId: 'my-resturant-74be1',
    storageBucket: 'my-resturant-74be1.appspot.com',
    iosBundleId: 'com.app.aiEnabledRestaurantControlAndOptimization',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC77ywoVqyr4VgL6Cc8aJldAABZAoHQ984',
    appId: '1:513181349032:android:bf2733980c8dad1ee5be9d',
    messagingSenderId: '513181349032',
    projectId: 'my-resturant-74be1',
    storageBucket: 'my-resturant-74be1.appspot.com',
  );

}